# Generated by Django 5.0.1 on 2025-11-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metric_data', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.company')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['company', 'metric_type', 'period_end'], name='analytics_d_company_14268e_idx')],
            },
        ),
    ]
