# Generated by Django 5.0.1 on 2025-11-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargosnap_integration', '0001_initial'),
        ('inspections', '0002_add_container_vehicle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='cargosnap_file',
            field=models.ForeignKey(blank=True, help_text='Arquivo CargoSnap vinculado a esta inspeção', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='cargosnap_integration.cargosnapfile'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='imported_from_cargosnap',
            field=models.BooleanField(default=False, help_text='Indica se esta inspeção foi importada do CargoSnap'),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='cargosnap_upload',
            field=models.ForeignKey(blank=True, help_text='Upload CargoSnap de origem desta foto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_photos', to='cargosnap_integration.cargosnapupload'),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='photo_source',
            field=models.CharField(choices=[('MOBILE', 'Câmera Mobile'), ('UPLOAD', 'Upload Manual'), ('CARGOSNAP', 'CargoSnap')], default='MOBILE', max_length=20),
        ),
    ]
