# Generated by Django 5.0.1 on 2025-11-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allow_skip_steps', models.BooleanField(default=False)),
                ('auto_generate_report', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('inspection_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='inspections.inspectiontype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_forms', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text Input'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Date & Time'), ('TEXTAREA', 'Text Area'), ('SELECT', 'Dropdown'), ('MULTISELECT', 'Multiple Select'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio Buttons'), ('EMAIL', 'Email'), ('PHONE', 'Phone Number'), ('URL', 'URL'), ('FILE', 'File Upload')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('sequence', models.IntegerField(default=0)),
                ('width', models.CharField(default='full', max_length=20)),
                ('show_if_field', models.CharField(blank=True, max_length=100)),
                ('show_if_value', models.CharField(blank=True, max_length=200)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.workflowform')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('FORM', 'Fill Form'), ('PHOTO', 'Take Photo'), ('VIDEO', 'Record Video'), ('SCAN', 'Scan Reference'), ('SIGNATURE', 'Collect Signature'), ('APPROVAL', 'Approval Required'), ('NOTIFICATION', 'Send Notification'), ('CUSTOM', 'Custom Action')], max_length=20)),
                ('sequence', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_skippable', models.BooleanField(default=False)),
                ('min_photos', models.IntegerField(default=0)),
                ('max_photos', models.IntegerField(blank=True, null=True)),
                ('condition_field', models.CharField(blank=True, max_length=100)),
                ('condition_operator', models.CharField(blank=True, max_length=20)),
                ('condition_value', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('workflow', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('current_step_number', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_data', models.JSONField(blank=True, default=dict)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_execution', to='inspections.inspection')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflows.workflow')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_executions', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='workflows.workflowexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['step__sequence'],
                'unique_together': {('execution', 'step')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('file_url', models.URLField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='workflows.workflowexecution')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='workflows.workflowformfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='workflows.workflowform')),
                ('step_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='workflows.workflowstepexecution')),
            ],
            options={
                'ordering': ['field__sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_links', to='workflows.workflowform')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_links', to='workflows.workflowstep')),
            ],
            options={
                'unique_together': {('step', 'form')},
            },
        ),
    ]
